### ISSUE TITLE
Is there data available?

### ISSUE THREAD

**Issue by zhouhao-learning** [markovmodel/deeptime#24]
Hello, I am paying attention to your paper "VAMPnets for deep learning of molecular kinetics". I want to see what the data should look like first. So, is it possible to provide the download address of the data?

**Comment by amardt** [comment]
Hey,
you can access the data we use with the module data_generator in our package. The example notebooks show how to use it. The toy models will be generated on the fly.
For alanine dipeptide you need additionally the [mdshare](https://markovmodel.github.io/mdshare/) package for downloading the data from our server.
Unfortunately, we are not allowed to share the NTL9 data, which is kindly provided by the D.E. Shaw for science purposes. If you are interested in these you have to contact them by yourself.

Hope this helps!
Best,
Andreas

**Comment by zhouhao-learning** [comment]
@amardt 
ok, Thanks you very much
