### ISSUE TITLE
What does a visual picture mean?

### ISSUE THREAD

**Issue by zhouhao-learning** [markovmodel/deeptime#27]
Here are four pictures that I got by executing example / Alanine_dipeptide_multiple_files, but I can't understand what they mean, so can I explain them in a nutshell?
The picture is shown below:
![1](https://user-images.githubusercontent.com/24581773/47208680-00c72480-d3c1-11e8-9ddf-649e4d340d8c.png)
![default](https://user-images.githubusercontent.com/24581773/47208687-058bd880-d3c1-11e8-96d2-d91c225a5682.png)
![default](https://user-images.githubusercontent.com/24581773/47208688-07559c00-d3c1-11e8-95be-e8c329026322.png)
![default](https://user-images.githubusercontent.com/24581773/47208691-0886c900-d3c1-11e8-91d2-22b11aaa1d3a.png)

Thank you very much!

**Comment by amardt** [comment]
Hey,

so I really recommend to have a look in the paper, there these kinds of figures and the theory behind it are explained. 
But in a nutshell:
1. Its a state separation plot. Each color represents a state (where the output node with the highest activation wins). For Ala-Dipeptide with 4 output nodes you hope that the model sets 2 states on the left and 2 on the rigth side of this plot. (So your model is not optimal)
2. Its a similar plot but this time for each output node (state) you plot the activation for each input.

After you have a Markov State Model you can test it with the the implied timescales (ITS) and the Chapman-Kolmogorov Test (CK-Test).

3. ITS plot, where you get for each process a line. The processes you find (the ones not in the gey area) should be converged.
4. CK-test. You check if prediciton with a model which is estimated on tau agrees with a model estimated on n*tau. Meaning: The red and the blue line should be on top of each other.

Again: The paper states these stuff in far more detail.
Best
Andreas

**Comment by zhouhao-learning** [comment]
@amardt 
Ok, thank you very much, mainly because I don't have knowledge of molecular dynamics, so I don't understand your paper.
