### ISSUE TITLE
test_toymodel.py fails

### ISSUE THREAD

**Issue by yabmtm** [markovmodel/deeptime#31]
When running python setup.py test, I receive failures for the toy models.
The installation works fine, but am curious whether these toy models are deprecated/ from an older version or if this would cause errors when using the module with my environment.

I have attached the output of python setup.py test &> test.log
[test.log](https://github.com/markovmodel/deeptime/files/3535874/test.log)

**Comment by clonker** [comment]
A wild guess: your numpy is older than 1.13.0, that is when check_valid was introduced into numpy.random.multivariate_gaussian.

**Comment by yabmtm** [comment]
Thanks for the reply!
Looks like I have 1.17.0. I'm adding my current conda environment as well for reference.
[env.txt](https://github.com/markovmodel/deeptime/files/3536217/env.txt)

as an update, I've been able to get the models to work with my data, so this isn't especially an issue for me anymore. I'll close this issue unless anyone else feels it's important.
