### ISSUE TITLE
A question about whitening/centering transformations

### ISSUE THREAD

**Issue by gongshuai0606** [markovmodel/deeptime#37]
Hi, it seems that the line 340 `x = x.mm(self.mul)` of deeptime/time-lagged-autoencoder/tae/utils.py should be` x = self.mul.mm(x)` according to Zero-phase Component Analysis Whitening formula Z=VD^(−1/2)V^TX

**Comment by clonker** [comment]
possibly, however this project is not actively maintained anymore. i currently don't have the time to look into it, but you may check out https://github.com/deeptime-ml/deeptime .

**Comment by YunruiQIU** [comment]
> Not really, that depends on the shape of input trajectories/ featurized data, obviously, the codes of time-lagged autencoder codes are based on data which has shape (length, dimensions of features/coordinates). So original codes should be right.

**Comment by gongshuai0606** [comment]
> > Not really, that depends on the shape of input trajectories/ featurized data, obviously, the codes of time-lagged autencoder codes are based on data which has shape (length, dimensions of features/coordinates). So original codes should be right.

Thank you very much. I understand now
